name: CI/CD - PVDH

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout du code
      uses: actions/checkout@v3

    # Backend (FastAPI)
    - name: ğŸ Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: ğŸ“¦ Installer les dÃ©pendances backend
      working-directory: ./pandemie_api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: âœ… Lancer les tests backend
      working-directory: ./pandemie_api
      env:
        DATABASE_URL: "sqlite:///./test.db"
      run: |
        pytest


    # Frontend (React)
    - name: ğŸ§± Setup Node.js pour React
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: ğŸ“¦ Installer les dÃ©pendances frontend
      working-directory: ./front
      run: |
        npm install


    - name: âš™ï¸ Build du frontend React
      working-directory: ./front
      run: |
        npm run build
    
    # Docker - Build & Push
    - name: ğŸ³ Connexion Ã  Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ—ï¸ Construction de l'image Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tonimage:${{ github.ref_name }} .

    - name: ğŸ“¤ Push de l'image Docker
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/tonimage:${{ github.ref_name }}
