name: CI/CD - IA

on:
  push:
    paths:
      - 'IA/**'
      - '.github/workflows/ia.yml'

jobs:
  build-ia:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ³ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ Build Docker image
        run: docker build -t quentincrn08/ia:${{ github.ref_name }} ./IA

      - name: ğŸ“¤ Push Docker image
        run: docker push quentincrn08/ia:${{ github.ref_name }}
